apiVersion: v1
kind: ServiceAccount
metadata:
  name: bluestone
  labels:
    app: bluestone
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bluestone
  labels:
    app: bluestone
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bluestone
  labels:
    app: bluestone
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bluestone
subjects:
- kind: ServiceAccount
  name: bluestone
  namespace: default

# Made with Bob
